from typing import List, Tuple
from subset_iter import SubsetIterator

def solve_knapsack(costs: List[int], B: int) -> Tuple[List[int], int]:
    """
    Solves the 0/1 Knapsack problem using the SubsetIterator.
    """
    best_cost = -1
    best_indices_1based = []
    
    # Initialize the iterator
    iterator = SubsetIterator(costs, B)
    
    # Iterate over all feasible subsets generated by the backtracking
    for subset_0based in iterator.next():
        # Calculate current cost
        current_cost = sum(costs[i] for i in subset_0based)
        
        # Convert 0-based indices to 1-based and ensure they are sorted
        # (Since we process items 0 to n-1, they are naturally sorted)
        current_indices_1based = [i + 1 for i in subset_0based]
        
        # Selection Logic:
        # 1. Higher cost is preferred.
        # 2. If costs are equal, the lexicographically smaller 1-based list wins.
        if current_cost > best_cost:
            best_cost = current_cost
            best_indices_1based = current_indices_1based
        elif current_cost == best_cost:
            # Python compares lists lexicographically by default
            if current_indices_1based < best_indices_1based:
                best_indices_1based = current_indices_1based
                
    # If no subsets were found (should not happen as [] is usually valid), return 0
    if best_cost == -1:
        return [], 0

    return best_indices_1based, best_cost